# INGENIERIA DE CARACTERÍSTICAS

In [11]:
import sys
import os
import pandas as pd

In [3]:
sys.path.insert(0, '../src')
from src.funciones import random_forest_selection, conditional_entropy_selection, intersect_top_features

In [4]:
sys.path.insert(0, '../')
from src.parametros import rf_selection, ce_selection, features

In [5]:
#load data
dataTC= pd.read_csv('../data/processed/dataTC_processed.csv')
dataTC

,id,num__edad,num__campana,num__dias_ultima_camp,num__no_contactos,num__emp_var_rate,num__cons_price_idx,num__cons_conf_idx,num__euribor3m,num__nr_employed,...,cat__mes_may,cat__mes_otro,cat__dia_mon,cat__dia_otro,cat__dia_thu,cat__dia_tue,cat__dia_wed,cat__resultado_anterior_otro,cat__resultado_anterior_sin contacto,y
0,1,0.506494,0.00000,1.000000,0.000000,0.937500,0.991835,0.60251,0.962728,0.859848,...,1,0,1,0,0,0,0,0,1,0
1,2,0.246753,0.00000,1.000000,0.000000,0.937500,0.991835,0.60251,0.962728,0.859848,...,1,0,1,0,0,0,0,0,1,0
2,3,0.285714,0.00000,1.000000,0.000000,0.937500,0.991835,0.60251,0.962728,0.859848,...,1,0,1,0,0,0,0,0,1,0
3,4,0.493506,0.00000,1.000000,0.000000,0.937500,0.991835,0.60251,0.962728,0.859848,...,1,0,1,0,0,0,0,0,1,0
4,7,0.090909,0.00000,1.000000,0.000000,0.937500,0.991835,0.60251,0.962728,0.859848,...,1,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23094,32963,0.142857,0.00000,0.009009,0.166667,0.479167,1.000000,0.00000,0.203608,0.000000,...,0,1,0,1,0,0,0,1,0,0
23095,32964,0.363636,0.00000,1.000000,0.000000,0.479167,1.000000,0.00000,0.203608,0.000000,...,0,1,0,1,0,0,0,0,1,0
23096,32965,0.493506,0.02439,1.000000,0.000000,0.479167,1.000000,0.00000,0.203608,0.000000,...,0,1,0,1,0,0,0,0,1,0
23097,32966,0.337662,0.00000,1.000000,0.000000,0.479167,1.000000,0.00000,0.203608,0.000000,...,0,1,0,1,0,0,0,0,1,1
23098,32967,0.727273,0.04878,1.000000,0.166667,0.479167,1.000000,0.00000,0.203608,0.000000,...,0,1,0,1,0,0,0,1,0,0

In [6]:
ids = dataTC['id'].copy()
target= dataTC['y'].copy()
dataTC.drop(columns=['id'], inplace=True)

In [7]:
random_forest_selection = random_forest_selection(dataTC, rf_selection)
conditional_entropy_selection = conditional_entropy_selection(dataTC, ce_selection)
intersect_features = intersect_top_features(random_forest_selection, conditional_entropy_selection, features)

In [8]:
intersect_features

{'cat__contacto_celular',
 'cat__contacto_telefono fijo',
 'cat__mes_may',
 'cat__mes_otro',
 'cat__resultado_anterior_otro',
 'cat__resultado_anterior_sin contacto',
 'num__cons_conf_idx',
 'num__cons_price_idx',
 'num__dias_ultima_camp',
 'num__edad',
 'num__emp_var_rate',
 'num__euribor3m',
 'num__no_contactos',
 'num__nr_employed'}

In [9]:
dataTC = dataTC[list(intersect_features.intersection(dataTC.columns))]
dataTC

,cat__contacto_celular,num__cons_conf_idx,cat__mes_may,num__emp_var_rate,cat__mes_otro,num__euribor3m,num__no_contactos,num__dias_ultima_camp,cat__contacto_telefono fijo,num__cons_price_idx,cat__resultado_anterior_otro,num__nr_employed,num__edad,cat__resultado_anterior_sin contacto
0,0,0.60251,1,0.937500,0,0.962728,0.000000,1.000000,1,0.991835,0,0.859848,0.506494,1
1,0,0.60251,1,0.937500,0,0.962728,0.000000,1.000000,1,0.991835,0,0.859848,0.246753,1
2,0,0.60251,1,0.937500,0,0.962728,0.000000,1.000000,1,0.991835,0,0.859848,0.285714,1
3,0,0.60251,1,0.937500,0,0.962728,0.000000,1.000000,1,0.991835,0,0.859848,0.493506,1
4,0,0.60251,1,0.937500,0,0.962728,0.000000,1.000000,1,0.991835,0,0.859848,0.090909,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23094,1,0.00000,0,0.479167,1,0.203608,0.166667,0.009009,0,1.000000,1,0.000000,0.142857,0
23095,1,0.00000,0,0.479167,1,0.203608,0.000000,1.000000,0,1.000000,0,0.000000,0.363636,1
23096,1,0.00000,0,0.479167,1,0.203608,0.000000,1.000000,0,1.000000,0,0.000000,0.493506,1
23097,1,0.00000,0,0.479167,1,0.203608,0.000000,1.000000,0,1.000000,0,0.000000,0.337662,1
23098,1,0.00000,0,0.479167,1,0.203608,0.166667,1.000000,0,1.000000,1,0.000000,0.727273,0

In [12]:
dataTC_feature = pd.concat([ids, dataTC, target], axis=1)

**Guardar DataFrame en formato .csv**

In [13]:
#train_transformed.to_csv('train_processed.csv', index=False)
dataTC_feature.to_csv(os.path.join('../data/feature', 'dataTC_feature.csv'), index=False)

In [14]:
dataTC_feature

,id,cat__contacto_celular,num__cons_conf_idx,cat__mes_may,num__emp_var_rate,cat__mes_otro,num__euribor3m,num__no_contactos,num__dias_ultima_camp,cat__contacto_telefono fijo,num__cons_price_idx,cat__resultado_anterior_otro,num__nr_employed,num__edad,cat__resultado_anterior_sin contacto,y
0,1,0,0.60251,1,0.937500,0,0.962728,0.000000,1.000000,1,0.991835,0,0.859848,0.506494,1,0
1,2,0,0.60251,1,0.937500,0,0.962728,0.000000,1.000000,1,0.991835,0,0.859848,0.246753,1,0
2,3,0,0.60251,1,0.937500,0,0.962728,0.000000,1.000000,1,0.991835,0,0.859848,0.285714,1,0
3,4,0,0.60251,1,0.937500,0,0.962728,0.000000,1.000000,1,0.991835,0,0.859848,0.493506,1,0
4,7,0,0.60251,1,0.937500,0,0.962728,0.000000,1.000000,1,0.991835,0,0.859848,0.090909,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23094,32963,1,0.00000,0,0.479167,1,0.203608,0.166667,0.009009,0,1.000000,1,0.000000,0.142857,0,0
23095,32964,1,0.00000,0,0.479167,1,0.203608,0.000000,1.000000,0,1.000000,0,0.000000,0.363636,1,0
23096,32965,1,0.00000,0,0.479167,1,0.203608,0.000000,1.000000,0,1.000000,0,0.000000,0.493506,1,0
23097,32966,1,0.00000,0,0.479167,1,0.203608,0.000000,1.000000,0,1.000000,0,0.000000,0.337662,1,1
23098,32967,1,0.00000,0,0.479167,1,0.203608,0.166667,1.000000,0,1.000000,1,0.000000,0.727273,0,0